---

name: Feature Request
about: Suggest an idea for this project
title: "[FEATURE] "
labels: enhancement
assignees: ""
body:

- type: markdown
  attributes:
  value: |
  Thanks for taking the time to suggest a new feature!
- type: checkboxes
  id: self-check
  attributes:
  label: Self Check
  description: Please check these items before submitting
  options:
    - label: I have searched for existing feature requests
      required: true
    - label: I will use English to describe the feature request
      required: true
- type: textarea
  id: problem-description
  attributes:
  label: Is your feature request related to a problem?
  description: A clear and concise description of what the problem is.
  placeholder: I'm always frustrated when [...]
  validations:
  required: true
- type: textarea
  id: solution-description
  attributes:
  label: Describe the solution you'd like
  description: A clear and concise description of what you want to happen.
  placeholder: Please describe your proposed solution
  validations:
  required: true
- type: textarea
  id: alternatives
  attributes:
  label: Describe alternatives you've considered
  description: A clear and concise description of any alternative solutions or features you've considered.
  placeholder: Please describe any alternative solutions you've considered
  validations:
  required: true
- type: textarea
  id: additional-context
  attributes:
  label: Additional context
  description: Add any other context or screenshots about the feature request here.
  placeholder: Add any other context about the feature request here.
  validations:
  required: false
